LongName: Eastern Mennonite University
Description: Science Center

AddressLine1: 1200 Park Road
City: Harrisonburg

Country: United States
State: Virginia
Zipcode: "22802"

Latitude: 38.47209
Longitude: -78.8768
